name: Achapromo Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server: ftp.achapromo.com.br:21/
        ftp-username: achapr12
        ftp-password: ${{ secrets.ACHAPROMO_FTP_PASSWORD }}
        local-dir: ./public_html/